[book]
authors = ["Rico Hermans", "Daan van Berkel"]
language = "en"
multilingual = false
src = "src"
title = "Smorgasbord of Paradigms"

[output.html]
mathjax-support = true
additional-css = ["custom.css"]
